CREATE TABLE sep6_transaction (
    id VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(255),
    stellar_transaction_id VARCHAR(255),
    external_transaction_id VARCHAR(255),
    stellar_transactions JSON,
    status VARCHAR(255),
    status_eta BIGINT,
    more_info_url VARCHAR(255),
    kind VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    started_at TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    transfer_received_at TIMESTAMP WITHOUT TIME ZONE,
    type VARCHAR(255),
    request_asset_code VARCHAR(255),
    request_asset_issuer VARCHAR(255),
    amount_in VARCHAR(255),
    amount_in_asset VARCHAR(255),
    amount_out VARCHAR(255),
    amount_out_asset VARCHAR(255),
    amount_fee VARCHAR(255),
    amount_fee_asset VARCHAR(255),
    amount_expected VARCHAR(255),
    sep10_account VARCHAR(255),
    sep10_account_memo VARCHAR(255),
    withdraw_anchor_account VARCHAR(255),
    from_account VARCHAR(255),
    to_account VARCHAR(255),
    memo VARCHAR(255),
    memo_type VARCHAR(255),
    quote_id VARCHAR(255),
    message VARCHAR(255),
    refunds JSON,
    refund_memo VARCHAR(255),
    refund_memo_type VARCHAR(255),
    required_info_message VARCHAR(255),
    required_info_updates VARCHAR(255),
    CONSTRAINT pk_sep6_transaction PRIMARY KEY (id)
)
