package org.stellar.reference.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Customer(
  val id: String? = null,
  @SerialName("stellar_account") val stellarAccount: String? = null,
  val memo: String? = null,
  val memoType: String? = null,
  @SerialName("first_name") val firstName: String? = null,
  @SerialName("last_name") val lastName: String? = null,
  @SerialName("additional_name") val additionalName: String? = null,
  @SerialName("address_country_code") val addressCountryCode: String? = null,
  @SerialName("state_or_province") val stateOrProvince: String? = null,
  val city: String? = null,
  @SerialName("postal_code") val postalCode: String? = null,
  val address: String? = null,
  @SerialName("mobile_number") val mobileNumber: String? = null,
  @SerialName("email_address") val emailAddress: String? = null,
  @SerialName("birth_date") val birthDate: String? = null,
  @SerialName("birth_place") val birthPlace: String? = null,
  @SerialName("birth_country_code") val birthCountryCode: String? = null,
  @SerialName("bank_name") val bankName: String? = null,
  @SerialName("bank_account_number") val bankAccountNumber: String? = null,
  @SerialName("bank_account_type") val bankAccountType: String? = null,
  @SerialName("bank_number") val bankNumber: String? = null,
  @SerialName("bank_phone_number") val bankPhoneNumber: String? = null,
  @SerialName("bank_branch_number") val bankBranchNumber: String? = null,
  @SerialName("external_transfer_memo") val externalTransferMemo: String? = null,
  @SerialName("clabe_number") val clabeNumber: String? = null,
  @SerialName("cbu_number") val cbuNumber: String? = null,
  @SerialName("cbu_alias") val cbuAlias: String? = null,
  @SerialName("mobileMoneyNumber") val mobileMoneyNumber: String? = null,
  @SerialName("mobileMoneyProvider") val mobileMoneyProvider: String? = null,
  @SerialName("crypto_address") val cryptoAddress: String? = null,
  @SerialName("crypto_memo") val cryptoMemo: String? = null,
  @SerialName("tax_id") val taxId: String? = null,
  @SerialName("tax_id_name") val taxIdName: String? = null,
  @SerialName("occupation") val occupation: String? = null,
  @SerialName("employer_name") val employerName: String? = null,
  @SerialName("employer_address") val employerAddress: String? = null,
  @SerialName("language_code") val languageCode: String? = null,
  @SerialName("id_type") val idType: String? = null,
  @SerialName("id_country_code") val idCountryCode: String? = null,
  @SerialName("id_issue_date") val idIssueDate: String? = null,
  @SerialName("id_expiration_date") val idExpirationDate: String? = null,
  @SerialName("id_number") val idNumber: String? = null,
  @SerialName("photo_id_front") val photoIdFront: ByteArray? = null,
  @SerialName("photo_id_back") val photoIdBack: ByteArray? = null,
  @SerialName("notary_approval_of_photo_id") val notaryApprovalOfPhotoId: ByteArray? = null,
  @SerialName("ip_address") val ipAddress: String? = null,
  @SerialName("photo_proof_residence") val photoProofResidence: ByteArray? = null,
  val sex: String? = null,
  @SerialName("photo_proof_of_income") val photoProofOfIncome: ByteArray? = null,
  @SerialName("proof_of_liveness") val proofOfLiveness: ByteArray? = null,
  @SerialName("referral_id") val referralId: String? = null,
)
