package org.stellar.reference.dao

import org.jetbrains.exposed.sql.Table

/** Exposed table for the Customer model. */
object Customers : Table() {
  val id = varchar("id", 255).uniqueIndex()
  val stellarAccount = varchar("stellar_account", 255).index().nullable()
  val memo = varchar("memo", 255).nullable()
  val memoType = varchar("memo_type", 255).nullable()
  val firstName = varchar("first_name", 255).nullable()
  val lastName = varchar("last_name", 255).nullable()
  val additionalName = varchar("additional_name", 255).nullable()
  val addressCountryCode = varchar("address_country_code", 255).nullable()
  val stateOrProvince = varchar("state_or_province", 255).nullable()
  val city = varchar("city", 255).nullable()
  val postalCode = varchar("postal_code", 255).nullable()
  val address = varchar("address", 255).nullable()
  val mobileNumber = varchar("mobile_number", 255).nullable()
  val emailAddress = varchar("email_address", 255).nullable()
  val birthDate = varchar("birth_date", 255).nullable()
  val birthPlace = varchar("birth_place", 255).nullable()
  val birthCountryCode = varchar("birth_country_code", 255).nullable()
  val bankName = varchar("bank_name", 255).nullable()
  val bankAccountNumber = varchar("bank_account_number", 255).nullable()
  val bankAccountType = varchar("bank_account_type", 255).nullable()
  val bankNumber = varchar("bank_number", 255).nullable()
  val bankPhoneNumber = varchar("bank_phone_number", 255).nullable()
  val bankBranchNumber = varchar("bank_branch_number", 255).nullable()
  val externalTransferMemo = varchar("external_transfer_memo", 255).nullable()
  val clabeNumber = varchar("clabe_number", 255).nullable()
  val cbuNumber = varchar("cbu_number", 255).nullable()
  val cbuAlias = varchar("cbu_alias", 255).nullable()
  val mobileMoneyNumber = varchar("mobile_money_number", 255).nullable()
  val mobileMoneyProvider = varchar("mobile_money_provider", 255).nullable()
  val cryptoAddress = varchar("crypto_address", 255).nullable()
  val cryptoMemo = varchar("crypto_memo", 255).nullable()
  val taxId = varchar("tax_id", 255).nullable()
  val taxIdName = varchar("tax_id_name", 255).nullable()
  val occupation = varchar("occupation", 255).nullable()
  val employerName = varchar("employer_name", 255).nullable()
  val employerAddress = varchar("employer_address", 255).nullable()
  val languageCode = varchar("language_code", 255).nullable()
  val idType = varchar("id_type", 255).nullable()
  val idCountryCode = varchar("id_country_code", 255).nullable()
  val idIssueDate = char("id_issue_date", 10).nullable()
  val idExpirationDate = char("id_expiration_date", 10).nullable()
  val idNumber = varchar("id_number", 255).nullable()
  val photoIdFront = binary("photo_id_front").nullable()
  val photoIdBack = binary("photo_id_back").nullable()
  val notaryApprovalOfPhotoId = binary("notary_approval_of_photo_id").nullable()
  val ipAddress = varchar("ip_address", 255).nullable()
  val photoProofResidence = binary("photo_proof_residence").nullable()
  val sex = varchar("sex", 255).nullable()
  val photoProofOfIncome = binary("photo_proof_of_income").nullable()
  val proofOfLiveness = binary("proof_of_liveness").nullable()
  val referralId = varchar("referral_id", 255).nullable()
}
