---
# SEP Server
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.fullName }}-ing-{{ .Values.service.name }}
  {{- if .Values.ingress.metadata }}
    {{- range $key, $value := .Values.ingress.metadata }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.fullName }}-ing-{{ .Values.service.name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.tls.host }}
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}      
  {{- end }}
  {{- if .Values.ingress.rules }}
  rules:
  {{- range .Values.ingress.rules.hosts }}
  - host: {{ tpl .host $ }}
    http:
      paths:
        - path: {{ .path }}
          pathType: {{ .pathType| quote }}
          backend:
            service:
              name: {{ tpl .backend.serviceName $ }}
              port:
                number: {{ tpl .backend.servicePort $ }}
  {{- end }}
  {{- end }}


{{- $root := . }}
{{- $stellarObserver := (.Values.stellarObserver) }}
{{- if $stellarObserver.enabled }}
---
# Stellar Observer
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.fullName }}-ing-{{ .Values.service.name }}-observer
  {{- if .Values.ingress.metadata }}
    {{- range $key, $value := .Values.ingress.metadata }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.fullName }}-ing-{{ .Values.service.name }}-observer
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ $stellarObserver.ingress.tls.host }}
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}      
  {{- end }}
  {{- if .Values.ingress.rules }}
  rules:
  {{- range $stellarObserver.ingress.rules.hosts }}
  - host: {{ tpl .host $ }}
    http:
      paths:
        - path: {{ .path }}
          pathType: {{ .pathType | quote }}
          backend:
            service:
              name: {{ $root.Values.fullName }}-svc-{{ $root.Values.service.name }}-observer
              port:
                number: {{ $stellarObserver.deployment.port | default 8083 }}
  {{- end }}
  {{- end }}
{{- end }}