# Configuration Description - set depositInfoGeneratorType: api, this will tell Anchor Platform to contact the
#                              Anchor Reference Server for a destination account/memo to be used in a SEP-31 transaction
#                           - set distributionWallet: GBN4NNCDGJO4XW4KQU3CBIESUJWFVBUZPOKUZHT7W7WRB7CWOA7BXVQF, in
#                              the Anchor Reference Server
version: '2'
services:
  anchor-platform-server:
    volumes:
      # add mounts for the new config directory
      - ./anchor-platform-unique-address:/config_override
    ports:
      # override ports, do not append
      - "8080:8080"

  anchor-reference-server:
    volumes:
      # add mounts for the new config directory
      - ./anchor-platform-unique-address:/config_override
    ports:
      # override ports, do not append
      - "8081:8081"

  db:
    environment:
      - PGPORT=5440
    ports:
      # override ports, do not append
      - "5440:5440"

  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    ports:
      # TODO: might need to change this
      - 29092:29092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:29092

  end-to-end-tests:
    command: --domain host.docker.internal:8080 --tests sep31_flow --tests sep31_flow_with_sep38