{
 "title": "Anchor Platform Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  { "title": "Anchor Platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{app=\"$application\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"$application\"}*1000"
    }
   ]
  },
  {
   "title": "HTTP Requests (Non - 2XX)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{app=\"$application\", uri!=\"/actuator/prometheus\", uri!=\"/**\", status!~\"200|201|202\"})"
    }
   ]
  },
  {
   "title": "Transaction Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by(status) (increase(sep31_transaction_total{app=\"$application\",status=\"error\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Log (Errors)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by(status) (increase(sep31_transaction_total{app=\"$application\",status=\"error\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Log (Warnings)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logger_total{app=\"$application\",type=\"warn\"}"
    }
   ]
  },
  { "title": "Payment Observer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Payment Observer (Payments Received Count)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "changes(payment_received_total{}[$__range]) + 1",
     "legendFormat": "asset - {{asset}}"
    }
   ]
  },
  {
   "title": "Payment Observer (Payments Received Amount)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(payment_received_total{app=\"$application\"}[$__range])",
     "legendFormat": "asset - {{asset}}"
    }
   ]
  },
  { "title": "SEP-31 Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Transactions - Completed (DB Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sep31_transaction_db{app=\"$application\", status=\"completed\"}"
    }
   ]
  },
  {
   "title": "Transactions - Pending Receiver (DB Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sep31_transaction_db{app=\"$application\", status=\"pending_receiver\"}"
    }
   ]
  },
  {
   "title": "Transactions - Pending Sender (DB Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sep31_transaction_db{app=\"$application\", status=\"pending_sender\"}"
    }
   ]
  },
  {
   "title": "Transactions - Pending Customer Info (DB Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sep31_transaction_db{app=\"$application\", status=\"pending_customer_info_update\"}"
    }
   ]
  },
  {
   "title": "Transactions - Pending External (DB Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sep31_transaction_db{app=\"$application\", status=\"pending_external\"}"
    }
   ]
  },
  {
   "title": "Transactions - Pending Stellar (DB Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sep31_transaction_db{app=\"$application\", status=\"pending_stellar\"}"
    }
   ]
  },
  {
   "title": "Transactions - Completed (Range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by(status) (increase(sep31_transaction_total{app=\"$application\", status=\"completed\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Transactions - Pending Receiver (Range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by(status) (increase(sep31_transaction_total{app=\"$application\", status=\"pending_receiver\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Transactions - Pending Sender (Range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by(status) (increase(sep31_transaction_total{app=\"$application\", status=\"pending_sender\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Transactions - Pending Customer Info (Range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor (sum by(status) (increase(sep31_transaction_total{app=\"$application\", status=\"pending_customer_info_update\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Transactions - Pending Customer Info (Range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor (sum by(status) (increase(sep31_transaction_total{app=\"$application\", status=\"pending_external\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Transactions - Pending Customer Info (Range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor (sum by(status) (increase(sep31_transaction_total{app=\"$application\", status=\"pending_stellar\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Transaction Status (Range) - WIP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum by(status) (increase(sep31_transaction_total{app=\"$application\"}[$__range])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Anchor Platform Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Request Distribution Count",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{app=\"$application\", uri!=\"/actuator/prometheus|/**\", method!=\"OPTIONS\"}[$__range])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Request Error Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=\"$application\", uri!=\"/**\", uri!=\"/actuator/prometheus\", status!=\"200\", status!=\"201\", status!=\"202\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Published Events",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(event_published_total{app=\"$application\"}[$__range])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$application\", uri!=\"/**\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "requests"
    },
    {}
   ]
  },
  {
   "title": "Request Latency (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{app=\"$application\", uri!=\"/**\", uri!=\"/actuator/prometheus\", method!=\"OPTIONS\"}",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{app=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{app=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{app=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{app=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "process_files_open_files{app=\"$application\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{app=\"$application\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=\"$application\", area=\"heap\"}) / 1000 / 1000\n",
     "legendFormat": "Heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{app=\"$application\", area=\"nonheap\"}) / 1000 / 1000\n",
     "legendFormat": "Non-Heap"
    }
   ]
  }
 ]
}