package org.stellar.anchor.api.webhook.fireblocks;

public enum EventType {
  TRANSACTION_CREATED,
  TRANSACTION_STATUS_UPDATED,
  TRANSACTION_APPROVAL_STATUS_UPDATED,
  VAULT_ACCOUNT_ADDED,
  VAULT_ACCOUNT_ASSET_ADDED,
  INTERNAL_WALLET_ASSET_ADDED,
  EXTERNAL_WALLET_ASSET_ADDED,
  EXCHANGE_ACCOUNT_ADDED,
  FIAT_ACCOUNT_ADDED,
  NETWORK_CONNECTION_ADDED
}
